### ISSUE TITLE
Replace PIL by pillow

### ISSUE THREAD

**Issue by ghost** [pinax/pinax-project-symposion#2]
The current installation of requirements.txt fails with PIL:
«
Downloading/unpacking PIL==1.1.7 (from -r requirements.txt (line 21))
  Could not find any downloads that satisfy the requirement PIL==1.1.7 (from -r requirements.txt (line 21))
  Some externally hosted files were ignored (use --allow-external PIL to allow).
»

**Comment by mjumbewu** [comment]
Looks like this was fixed in commit 49c8f9490. Should be safe to close this.

**Comment by ossanna16** [comment]
Thank you @mjumbewu! Closing this now.
